name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:            # allow the bot to push
  contents: write
  pull-requests: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         # so auto-commit can push

      # Ruff: auto-fix code
      - uses: astral-sh/ruff-action@v3
        with:
          src: "src tests"
          args: "check --fix --output-format github"

      # Auto-commit any changes Ruff made
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: ruff auto-fixes"
          branch: ${{ github.head_ref || github.ref_name }}
          push_options: --force
      
      # Python setup for tests
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
          python -m pytest -q