name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        pip install -e .

    - name: Ruff lint
      run: ruff check src tests --output-format github

    - name: PyTest
      run: python -m pytest -q