name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ── Ruff: install + auto-fix + lint ──────────────────────────────
      - uses: astral-sh/ruff-action@v3
        with:
          src: "src tests"                   # directories to lint
          args: "check --fix --output-format github"

      # ── Python setup for unit tests ─────────────────────────────────
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project & test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run PyTest
        run: python -m pytest -q